# Copyright 2021 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

server:
  port: 8080
  debug: true
  read_timeout_seconds: 360
  read_header_timeout_seconds: 360
  write_timeout_seconds: 360
  cors: ["*"]

database:
  request_timeout_sec: 5
  database: nodewatch-crawler-db
  collection: peers
  history_collection: history

resolver:
  request_timeout_sec: 3

fileOutput:
  path: "./crawler.out"

crawler:
  concurrency: 1
  connection_retries: 8
  update_freq_min: 12
  genesis_validators_root: "4b363db94e286120d76eb905340fdd4e54bfe9f06bf33ff6cf5ad27f511bfe95"
  fork_digest: "0xbba4da96"
kafka:
  topic: "eth_relay_monitor"
  bootstrap_servers: "kafka:9092"
  timeout: 10s