# Copyright 2021 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

server:
  port: 8080
  debug: true
  read_timeout_seconds: 360
  read_header_timeout_seconds: 360
  write_timeout_seconds: 360
  cors: ["*"]

database:
  request_timeout_sec: 5
  database: nodewatch-crawler-db
  collection: peers
  history_collection: history

resolver:
  request_timeout_sec: 3

fileOutput:
  path: "./crawler.out"

crawler:
  concurrency: 5
  connection_retries: 5
  update_freq_min: 5
  genesis_validators_root: "4b363db94e286120d76eb905340fdd4e54bfe9f06bf33ff6cf5ad27f511bfe95"
  genesis_time: 1606824023
  seconds_per_slot: 12
  slots_per_epoch: 32

# Leave digest blank for automatic generation (must have correct genesis validators root)
fork:
  altair:
    supported: false
  bellatrix:
    supported: false
  capella:
    supported: true
  deneb:
    supported: true

network:
  # mainnet | goerli | sepolia | custom
  name: mainnet
